title: S Mohamed Kalandar Sulaiman
logo: /assets/images/dp.jpg
description: Passionate software engineer with consistent efforts in learning new stuffs. Iam interested on working in distributed systems. I actively learn new technologies and apply in my work as well my personal projects. Primiarily a python devloper but would prefer to be language agnostic. Love backend engineering with essential front end skills . 
show_downloads: false
google_analytics: no
theme: jekyll-theme-minimal
show_maintained_by: false
show_hosted_by: false
show_view_project_link: false

